FORMAT: 1A

# LoL Improve API
LoL Improve APIARY is the documentation and mocking tool used inside the LoL Improve web application.
This is no public API, though, and CORS is not allowed, except on the mocking prototype.

# Group Replay
Replay related resources of the **LoLImprove API**

## Replays [/replays]
### List all Replays [GET]
+ Response 200 (application/json)

        [
            {
                id: 1
                user_id: 1,
                video_id: "QMujSbIkF8M",
                lane: "mid",
                champion: "syndra",
                matchup: "ahri",
                victory: true,
                kda: "17/4/8",
                description: "I struggled a lot during the laning phase and didn't ward at all. When and where should I had warded ?",
                duration: "25:01",
                patch: "4.19",
                replay_file: null,
                created_at: "2014-11-12 16:35:18",
                updated_at: "2014-11-12 16:35:18"
            },
            {
                id: 2
                user_id: 2,
                video_id: "QMujSbIkF8M",
                lane: "mid",
                champion: "ahri",
                matchup: "zed",
                victory: false,
                kda: "1/4/8",
                description: "I did a lot during the laning phase but didn't ward at all. When and where should I had warded ?",
                duration: "63:01",
                patch: "4.16",
                replay_file: null
                created_at: "2014-11-12 18:55:18",
                updated_at: "2014-11-19 10:34:02"
            }
        ]

### Create a Replay [POST]
**\<Authentificated>** Creates a new replay for the current user

+ Request (application/json)

        {
            user_id: 2,
            video_id: "QMujSbIkF8M",
            lane: "mid",
            champion: "ahri",
            matchup: "zed",
            victory: false,
            kda: "1/4/8",
            description: "I did a lot during the laning phase but didn't ward at all. When and where should I had warded ?",
            duration: "63:01",
            patch: "4.16",
            replay_file: null
            created_at: "2014-11-12 18:55:18",
            updated_at: "2014-11-19 10:34:02"
        }

+ Response 201 (application/json)

        {
            id: 2
            user_id: 2,
            video_id: "QMujSbIkF8M",
            lane: "mid",
            champion: "ahri",
            matchup: "zed",
            victory: false,
            kda: "1/4/8",
            description: "I did a lot during the laning phase but didn't ward at all. When and where should I had warded ?",
            duration: "63:01",
            patch: "4.16",
            replay_file: null
            created_at: "2014-11-12 18:55:18",
            updated_at: "2014-11-19 10:34:02"
        }

## Replay [/replays/{id}]
A single Replay object with all its details

+ Parameters
    + id (required, number) ... Numeric id` of the replay to retrieve

### Retrieve a replay [GET]
+ Response 200 (application/json)

        {
            id: 2
            user_id: 2,
            video_id: "QMujSbIkF8M",
            lane: "mid",
            champion: "ahri",
            matchup: "zed",
            victory: false,
            kda: "1/4/8",
            description: "I did a lot during the laning phase but didn't ward at all. When and where should I had warded ?",
            duration: "63:01",
            patch: "4.16",
            replay_file: null
            created_at: "2014-11-12 18:55:18",
            updated_at: "2014-11-19 10:34:02"
        }

### Update a replay [PATCH]
**\<Authentificated>** Updates the current user's replay

+ Request (application/json)

        {
            description: "Hello, world"
        }

+ Response 200 (application/json)

### Remove a Replay [DELETE]
+ Response 204

